# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 233a341ae1616ce1dd9f0bdf87df66e253fd3ea1374d53535e89f99c6054b64aec4162b5385186fe25ec294a25bd00618765034a4dfb99cc6badc8ac25e48bbe

test:
  secret_key_base: 5b4daccec767058b97385b89328e5b4cf3736e17c9e6b895804634d5f19de0e0109581aa7b6680125f5c0ca9291f5027c24ab0eb499dd74e88e56f8f0e40f242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
